language: python

python:
    - "2.7"

install:
    - pip install -U pip
    - pip install django flake8

script:
    - python manage.py test
    - flake8 --exclude polls/migrations/,manage.py  .
    #- python manage.py runserver 0:8000
