language: python

python:
  - "stable"

install:
  - pip3 install django flake8

before_script:
  - python3 manage.py migrate

script:
  - python3 manage.py test
  - flake8 --exclude polls/migrations/,manage.py .
