language: python

python:
  - "stable"

install:
  - pip install django flake8

before_script:
  - python manage.py migrate

script:
  - python manage.py test
  - flake8 --exclude polls/migrations/,manage.py .
